name 'autoproj-jenkins'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures autoproj-jenkins'
long_description 'Installs/Configures autoproj-jenkins'
version '0.1.0'
depends 'apache2'
depends 'jenkins'
depends 'sudo'
depends 'locale'
